import { ClerkProvider } from "@clerk/nextjs";
import logo from '@/assets/logo.svg';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: logo.src,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
