import { ClerkProvider } from "@clerk/nextjs";
import logo from "@/assets/logo.svg";
import "../globals.css";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: logo.src,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={twMerge(inter.className, "bg-dark-1")}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
